---
- name: Preprare the development machine with basic settings, packages and networking
  hosts: development

  roles:
    - role: hypervisor/proxmox 
      vars: 
       pve_group: all,
       pve_reboot_on_kernel_update: false

  tasks:
  
    - name: Install basic packages
      become: yes
      apt:
        update_cache: yes
        pkg:
          - git
          - nano
          - htop
          - curl
          - timeshift
        state: present
      register: apt_action
      retries: 100
      until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

    # https://pve.proxmox.com/wiki/Certificate_Management
