---
- name: Preprare the development machine with basic settings, packages and networking
  hosts: development

  tasks:
    ### Proxmox repository # https://github.com/chriswayg/ansible-proxmox/blob/master/tasks/main.yml
    - name: Remove Proxmox Enterprise repository
      apt_repository:
        repo: 'deb https://enterprise.proxmox.com/debian bullseye pve-enterprise'
        state: absent

    - name: Use Proxmox free repository
      apt_repository:
        repo: 'deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription'
        state: present

    - name: Install basic packages
      become: yes
      apt:
        update_cache: yes
        pkg:
          - git
          - nano
          - htop
          - curl
          - timeshift
          - python3-jmespath
        state: present
      register: apt_action
      retries: 100
      until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

    - name: Enable nested virtualization # https://pve.proxmox.com/wiki/Nested_Virtualization
      shell: |
        echo "options kvm-amd nested=1" > /etc/modprobe.d/kvm-amd.conf
        modprobe -r kvm_amd
        modprobe kvm_amd
