---
- name: Install Ceph
  hosts: machine

  tasks:
    - name: Install Ceph
      shell: "pveceph install"

    - name: Install Ceph
      shell: "pveceph init --network 192.168.0.0/16"

    - name: Create Monitor
      shell: "pveceph mon create"

    - name: Create Manager
      shell: "pveceph mgr create"
