---
- name: Configure Ceph
  hosts: development

  tasks:
    - name: Created the keyring to store the keys
      shell: "ceph-authtool --create-keyring /etc/ceph/ceph.client.radosgw.keyring"

    - name: Generated the keys and added them to the keyring
      shell: "ceph-authtool /etc/ceph/ceph.client.radosgw.keyring -n client.radosgw.{{ ansible_hostname }} --gen-key"

    - name: Added the proper capabilities
      shell: "ceph-authtool -n client.radosgw.{{ ansible_hostname }} --cap osd 'allow rwx' --cap mon 'allow rwx' /etc/ceph/ceph.client.radosgw.keyring"

    - name: Add the keys to the cluster
      shell: "ceph -k /etc/ceph/ceph.client.admin.keyring auth add client.radosgw.{{ ansible_hostname }} -i /etc/ceph/ceph.client.radosgw.keyring"

    - name: Copy the keyring
      shell: "cp /etc/ceph/ceph.client.radosgw.keyring /etc/pve/priv"

    - name: Insert/Update "Match User" configuration block in /etc/ceph/ceph.conf
      blockinfile:
        path: /etc/ceph/ceph.conf
        block: |
          [client.radosgw.{{ ansible_hostname }}]
              host = {{ ansible_hostname }}
              keyring = /etc/pve/priv/ceph.client.radosgw.keyring
              log file = /var/log/ceph/client.radosgw.$host.log
              rgw_dns_name = s3.dev.jakoberpf.net

    - name: Install radosgw
      become: yes
      apt:
        update_cache: yes
        pkg:
          - radosgw
        state: present
      register: apt_action
      retries: 100
      until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

    - name: Create systemd directory
      shell: "mkdir /etc/systemd/system/ceph-radosgw.target.wants"

    - name: Link keyring
      shell: "ln -s /lib/systemd/system/ceph-radosgw@.service /etc/systemd/system/ceph-radosgw.target.wants/ceph-radosgw@radosgw.radosgw.{{ ansible_hostname }}"

    - name: Reload systemd daemon
      shell: "systemctl daemon-reload"

    - name: Start systemd service
      shell: "systemctl start ceph-radosgw@radosgw.{{ ansible_hostname }}"

# https://docs.ceph.com/en/octopus/mgr/dashboard/#enabling-the-object-gateway-management-frontend
# https://devopstales.github.io/linux/proxmox-ceph-radosgw/
# https://pve.proxmox.com/wiki/User:Grin/Ceph_Object_Gateway
# https://base64.co.za/enable-amazon-s3-interface/
# https://computingforgeeks.com/configure-aws-s3-cli-for-ceph-object-gateway-storage/
# ceph osd pool create .rgw.root 128
# radosgw -f --cluster ceph --name client.radosgw.pve1 --setuser ceph --setgroup ceph
# https://www.symmcom.com/docs/how-tos/storages/how-to-configure-s3-compatible-object-storage-on-ceph