---
# ansible-galaxy install m4rcu5nl.zerotier-one

- name: Setup haproxy as loadbalancer in high aviability with keepalived
  hosts: machine

  vars:
    # zerotier_api_url
    zerotier_network_id: "{{ zerotier_network_id }}"
    zerotier_api_accesstoken: "{{ zerotier_accesstoken }}"
    zerotier_register_short_hostname: true
    zerotier_member_ip_assignments: "{{ zerotier_network_ip }}"
    zerotier_member_description: "The development machine"

  roles:
    - role: networking/zerotier
      become: true 
      vars:
        skip_install: true

  # curl -s https://install.zerotier.com | sudo bash
  # sudo zerotier-cli join <id>
  # sudo timeshift --create --comments "Zerotier is installed and joined the management network"
