# https://github.com/cloudflare/argo-tunnel-examples
- name: Preprare Development Machine
  hosts: machine

  vars:
    - account: "{{ cloudflared_account }}"
    - tunnel_id: "{{ cloudflared_tunnel_id }}"
    - tunnel_name: "{{ cloudflared_tunnel_name }}"
    - secret: "{{ cloudflared_secret }}"
    - web_zone: "{{ cloudflared_web_zone }}"

  tasks:
    - name: Setup virtual python enviroment for kolla openstack
      become: yes
      shell: wget -O /tmp/cloudflared-stable-linux-amd64.deb https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-amd64.deb

    - name: Setup virtual python enviroment for kolla openstack
      become: yes
      shell: dpkg -i /tmp/cloudflared-stable-linux-amd64.deb && rm /tmp/cloudflared-stable-linux-amd64.deb

    - name: Create a directory for the cloudflared configs
      become: yes
      ansible.builtin.file:
        path: /etc/cloudflared/
        state: directory

    - name: Create the cert.json file
      become: yes
      ansible.builtin.template:
        src: ../templates/cert.json.j2
        dest: "/etc/cloudflared/cert.json"

    - name: Create the config.yml file 
      become: yes
      ansible.builtin.template:
        src: ../templates/config.yml.j2
        dest: "/etc/cloudflared/config.yml"

    - name: Now we install the tunnel as a systemd service
      become: yes
      shell: cloudflared service install

    - name: Now we can start the tunnel
      become: yes
      shell: service cloudflared start