---
# ansible-galaxy install m4rcu5nl.zerotier-one

- name: Setup haproxy as loadbalancer in high aviability with keepalived
  hosts: machine

  vars:
    zerotier_network_id: 35c192ce9b8273fd
    zerotier_api_accesstoken: "{{ vault_zerotier_accesstoken }}"
    zerotier_register_short_hostname: true

  roles:
    - { role: m4rcu5nl.zerotier, become: true }

  # curl -s https://install.zerotier.com | sudo bash
  # sudo zerotier-cli join <id>
  # sudo timeshift --create --comments "Zerotier is installed and joined 35c192ce9b8273fd"
