---
- name: Preprare Development Machine
  hosts: machine

  tasks:

    - name: Install packages only when the apt process is not locked
      become: yes
      apt:    
        pkg:
          - git 
          - gcc
          - python3-dev 
          - python3-venv 
          - libffi-dev 
          - libssl-dev
        state: present
      register: apt_action
      retries: 100
      until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

    - name: Add IP address of all hosts to all hosts
      become: yes
      lineinfile:
        dest: /etc/hosts
        regexp: '.*openstack.dev.jakoberpf.de$'
        line: "192.168.0.200 openstack.dev.jakoberpf.de"
        state: present

    - name: Setup virtual python enviroment for kolla openstack
      shell: python3 -m venv $HOME/kolla-openstack

    - name: Source virtual python env and install/update pip
      shell: source $HOME/kolla-openstack/bin/activate && pip install -U pip
      args:
        executable: /bin/bash

    - name: Source virtual python env and install ansible
      shell: source $HOME/kolla-openstack/bin/activate && pip install 'ansible<2.10' # actually <3.0 but broken
      args:
        executable: /bin/bash

    - name: Create ansible config
      shell: |
        cat << EOF > $HOME/ansible.cfg
        [defaults]
        host_key_checking=False
        pipelining=True
        forks=100
        EOF

    - name: Run source and install kolla-ansible
      shell: source $HOME/kolla-openstack/bin/activate && pip install kolla-ansible
      args:
        executable: /bin/bash

    - name: Create a directory for the kolla configs
      become: yes
      ansible.builtin.file:
        path: /etc/kolla
        state: directory

    - name: Set permissions of kolla configs
      become: yes
      command: chown $USER:$USER /etc/kolla

    - name: Copy globals
      become: yes
      ansible.builtin.copy:
        src: ../configs/etc/kolla/globals.yml
        dest: /etc/kolla/globals.yml

    - name: Copy passwords
      become: yes
      ansible.builtin.copy:
        src: ../configs/etc/kolla/passwords.yml
        dest: /etc/kolla/passwords.yml

    - name: Copy inventory
      ansible.builtin.copy:
        remote_src: yes
        src: $HOME/kolla-openstack/share/kolla-ansible/ansible/inventory/all-in-one
        dest: .

    # source $HOME/kolla-openstack/bin/activate
    # kolla-ansible -i all-in-one bootstrap-servers
    # kolla-ansible -i all-in-one prechecks
    # kolla-ansible -i all-in-one deploy
    # kolla-ansible -i all-in-one post-deploy
    # kolla-ansible -i all-in-one check

    # kolla-ansible -i all-in-one reconfigure