---
- name: Preprare Development Machine
  hosts: machine

  roles:

    - name: common/sudoers
      vars:
        security_sudoers_passwordless: ["jakoberpf"]

  tasks:

    - name:
      become: yes
      community.general.ufw:
        rule: allow
        name: OpenSSH

    # - name: Allow everything and enable UFW
    #   become: yes
    #   community.general.ufw:
    #     state: enabled

    - name: Install basic packages
      become: yes
      apt:
        update_cache: yes        
        pkg:
          - git 
          - nano 
          - htop 
          - curl
          - vino
          - snapd
          - timeshift
        state: present
      register: apt_action
      retries: 100
      until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)
