---
# ansible-galaxy install m4rcu5nl.zerotier-one

- name: Configure Zerotier
  hosts: machine

  roles:
    - role: networking/zerotier
      become: true 
      vars:
        skip_install: true
        zerotier_register_short_hostname: true
        zerotier_member_description: "Managed by Ansible"
        zerotier_member_identiy_private: "../artifacts/zerotier/identity.secret"
        zerotier_member_identiy_public: "../artifacts/zerotier/identity.public"

  # tasks:
  # sudo timeshift --create --comments "Zerotier is installed and joined the management network"
